from environs import Env

env = Env()
env.read_env()

DICT_ENVS = {}

DICT_ENVS["BASE_IP"] = env.str("BASE_IP")
DICT_ENVS["BASE_PORT"] = env.int("BASE_PORT")
DICT_ENVS["USER_NAME"] = env.str("USER_NAME")
DICT_ENVS["USER_PASS"] = env.str("USER_PASS")
DICT_ENVS["DB_NAME"] = env.str("DB_NAME")
DICT_ENVS["EMAIL_HOST"] = env.str("EMAIL_HOST")
DICT_ENVS["EMAIL_PORT"] = env.int("EMAIL_PORT")
DICT_ENVS["EMAIL_USERNAME"] = env.str("EMAIL_USERNAME")
DICT_ENVS["EMAIL_PASSWORD"] = env.str("EMAIL_PASSWORD")
DICT_ENVS["SECRET_KEY"] = env.str("SECRET_KEY")
DICT_ENVS["ALGORITHM"] = env.str("ALGORITHM")
DICT_ENVS["ACCESS_TOKEN_EXPIRE_MINUTES"] = env.str("ACCESS_TOKEN_EXPIRE_MINUTES")
